function information = environment
%ENVIRONMENT Report CPU, parallel-pool, and GPU execution capabilities.

information = struct();
information.matlabRelease = string(version('-release'));
information.logicalCores = feature('numcores');
information.parallelToolboxLicensed = license('test','Distrib_Computing_Toolbox');
information.gpuCount = gpuDeviceCount("available");
information.gpus = repmat(struct('name',"",'computeCapability',"", ...
    'supportsDouble',false,'totalMemoryBytes',0,'availableMemoryBytes',0), ...
    information.gpuCount,1);
for index = 1:information.gpuCount
    device = gpuDevice(index);
    information.gpus(index) = struct( ...
        'name',string(device.Name), ...
        'computeCapability',string(device.ComputeCapability), ...
        'supportsDouble',logical(device.SupportsDouble), ...
        'totalMemoryBytes',double(device.TotalMemory), ...
        'availableMemoryBytes',double(device.AvailableMemory));
end
end
