function configuration = cylinder_vortex_entry_config
%CYLINDER_VORTEX_ENTRY_CONFIG Reproducible production experiment settings.

repositoryRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(repositoryRoot);
startup;

configuration = struct();
configuration.name = "cylinder-vortex-entry";
configuration.geometry = struct( ...
    'SampleRadius',2, ...
    'SampleHeight',4, ...
    'OuterRadius',6, ...
    'OuterHeight',10, ...
    'Hmax',0.4);
configuration.physics = struct( ...
    'Kappa',5, ...
    'MaximumField',0.8, ...
    'RampTime',10, ...
    'NoiseAmplitude',1e-3, ...
    'RandomSeed',1729);
configuration.time = struct( ...
    'StartTime',0, ...
    'StopTime',30, ...
    'TimeStep',0.05, ...
    'StoreEvery',10);
configuration.solver = struct( ...
    'RelativeTolerance',1e-7, ...
    'AbsoluteTolerance',1e-9, ...
    'MaximumIterations',40, ...
    'Relaxation',0.7);
configuration.execution = tdgl.compute.execution("auto", ...
    'MinimumUnknowns',15000,'MemoryFraction',0.3,'AllowFallback',true);
configuration.storage = struct( ...
    'ResultsRoot',string(fullfile(repositoryRoot,'results')), ...
    'CheckpointEvery',1, ...
    'ResumeDirectory',"");
end
