%COUPLED_UNIFORM_RELAXATION Run a self-consistent zero-field TDGL-MQS case.
repositoryRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(repositoryRoot);
startup;
mesh = tdgl.geometry.boxMesh([2 2 2]);
model = struct( ...
    'u',1,'a',1,'b',1,'K',1, ...
    'conductivity',1,'muInv',1,'kappa',1, ...
    'sourceCurrent',[0 0 0]);
boundary = tdgl.boundary.tangentialDirichlet( ...
    mesh,mesh.topology.boundaryFaceIds,[0 0 0]);
initialState = tdgl.state.create(mesh, ...
    0.25*ones(size(mesh.nodes,1),1), ...
    zeros(double(mesh.topology.nEdges),1), ...
    zeros(size(mesh.nodes,1),1));
meanMagnitude = struct('Name',"meanMagnitude",'Evaluate', ...
    @(~,~,current,~,~,~,~) mean(abs(current.orderParameter)));

result = tdgl.time.integrateCoupled( ...
    mesh,initialState,model,boundary, ...
    'StopTime',0.25,'TimeStep',0.05,'Observers',meanMagnitude);

fprintf('Initial mean |psi|: %.6f\n',mean(abs(initialState.orderParameter)));
fprintf('Final mean |psi|:   %.6f\n', ...
    mean(abs(result.finalState.orderParameter)));
fprintf('Final ||A||:        %.3e\n',norm(result.finalState.edgePotential));
fprintf('Maximum coupling iterations: %d\n', ...
    max([result.stepDiagnostics.iterations]));
