%UNIFORM_ORDER_PARAMETER_RELAXATION Relax a homogeneous TDGL state.
startup;
mesh = tdgl.geometry.boxMesh([2 2 2]);
model = struct( ...
    'u',1,'a',1,'b',1,'K',1, ...
    'edgePotential',zeros(double(mesh.topology.nEdges),1), ...
    'scalarPotential',0);
initialState = 0.25*ones(size(mesh.nodes,1),1);
energyObserver = struct('Name',"freeEnergy",'Evaluate', ...
    @(~,~,current,currentModel,~,~) ...
    totalEnergy(mesh,current,currentModel));
result = tdgl.time.integrateOrderParameter( ...
    mesh,initialState,model,'StopTime',1,'TimeStep',0.05, ...
    'Observers',energyObserver);

fprintf('Initial mean |psi|: %.6f\n',mean(abs(initialState)));
fprintf('Final mean |psi|:   %.6f\n',mean(abs(result.finalState)));

function value = totalEnergy(mesh,orderParameter,model)
energy = tdgl.post.orderParameterEnergy(mesh,orderParameter,model);
value = energy.total;
end
