function information = version
%VERSION Return solver-library version information.

information = struct( ...
    'Name', "3D Finite Element TDGL", ...
    'Version', "0.1.0-dev", ...
    'Stage', "exact-sequence finite-element foundation");
end
