function information = version
%VERSION Return solver-library version information.

information = struct( ...
    'Name', "3D Finite Element TDGL", ...
    'Version', "0.3.0-dev", ...
    'Stage', "TDGL-MQS reference solver with transport terminals");
end
