function information = version
%VERSION Return solver-library version information.

information = struct( ...
    'Name', "3D Finite Element TDGL", ...
    'Version', "0.2.0-dev", ...
    'Stage', "staggered self-consistent TDGL-MQS reference solver");
end
