function report = validate(mesh)
%VALIDATE Check canonical tetrahedral-mesh invariants.

required = {'nodes','cells','regionIds','topology','geometry','faceTags'};
for index = 1:numel(required)
    if ~isfield(mesh, required{index})
        error('tdgl:mesh:MissingField', ...
            'Canonical mesh is missing field "%s".', required{index});
    end
end

if any(mesh.geometry.detJ <= 0)
    error('tdgl:mesh:InvalidOrientation', ...
        'All canonical tetrahedra must have positive orientation.');
end
if numel(mesh.regionIds) ~= size(mesh.cells,1)
    error('tdgl:mesh:RegionSizeMismatch', ...
        'There must be exactly one region ID per tetrahedron.');
end

[G, C, D] = tdgl.topology.incidenceMatrices(mesh);
curlGradientResidual = nnz(C*G);
divergenceCurlResidual = nnz(D*C);
if curlGradientResidual ~= 0 || divergenceCurlResidual ~= 0
    error('tdgl:mesh:BrokenExactSequence', ...
        'Mesh incidence operators do not form a chain complex.');
end

report = struct( ...
    'nNodes', size(mesh.nodes,1), ...
    'nEdges', double(mesh.topology.nEdges), ...
    'nFaces', double(mesh.topology.nFaces), ...
    'nCells', size(mesh.cells,1), ...
    'minimumVolume', min(mesh.geometry.volume), ...
    'maximumVolume', max(mesh.geometry.volume), ...
    'curlGradientNonzeros', curlGradientResidual, ...
    'divergenceCurlNonzeros', divergenceCurlResidual);
end
